apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-apps
  template:
    metadata:
      labels:
        app: books-apps
    spec:
      containers:
      - name: books-apps
        image: adebisibiola/book_application:26416
        resources:
          request: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-apps
spec:
  type: LoadBalancer
  selector:
    app: books-apps
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
